---

- name: "01.1 - print some info"
  debug:
    msg: "Running startup script on [{{ k8s_node_name }}] node with type of [{{ k8s_node_type }}]..."

- name: "01.2 - configure tty appearance"
  template:
    src: bash.aliases.sh
    dest: "{{ item.dest }}"
    owner: "{{ item.owner|default(0) }}"
    group: "{{ item.group|default(0) }}"
  become: "{{ item.become|bool }}"
  with_items:
    - dest: /root/.bashrc
      become: yes
    - dest: /home/ubuntu/.bash_aliases
      become: yes
      owner: ubuntu
      group: ubuntu
