---

- name: "03.1 - make sure grub.d directory is created"
  file:
    path: "{{ __k8s_grub_d_dir }}"
    state: directory
  become: yes

- name: "03.2 - configure grub boot-loader"
  copy:
    content: |
      GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} cgroup_enable=memory swapaccount=1"
    dest: "{{ __k8s_grub_d_conf_file }}"
  register: _grub_config
  become: yes
  check_mode: no
  notify:
    - grub-update-config

- meta: flush_handlers

- name: "03.3.(remote) - restart the system if required"
  reboot:
    msg: "WARNING: a grub config has been changed recently - restart in order to apply all the changes!"
  become: yes
  check_mode: no
  when:
    - inventory_hostname not in ['localhost', '127.0.0.1']
    - _grub_config is defined and _grub_config is changed

- name: "03.3.(local) - restart the system if required"
  shell:
    cmd: "nohup bash -c 'sleep 5 && shutdown -r now' &"
  args:
    warn: no
  become: yes
  async: 0
  poll: 0
  ignore_errors: yes
  check_mode: no
  when:
    - inventory_hostname in ['localhost', '127.0.0.1']
    - _grub_config is defined and _grub_config is changed
