---

- name: "06.1 - remove swap entry from /etc/fstab"
  mount:
    name: swap
    fstype: swap
    state: absent
  become: yes

- name: "06.2 - disable swap"
  shell:
    cmd: swapoff -a
  args:
    warn: no
  become: yes
  changed_when: no
